### ISSUE TITLE
Wrong VCD path is passed to GTKWave (Windows)

### ISSUE THREAD

**Issue by trexxet** [j054n/dglog#1]
```
Trying GTKWave with file /c:/shitcode/hdl/dflipflop/build/dump.vcd
```
The path is prepended with `/`, which causes GTKWave silently failing to open the VCD

**Comment by j054n** [comment]
This extension was not tested previously on Windows filesystem.
Now, I have added a correction and tested it, I have generated version 1.0.2.
Update it please if it's not done automatically.
Thanks for your comments.

**Comment by trexxet** [comment]
Now it works fine, thanks!
